name: Update gist
on:
  repository_dispatch:
    types: [build-event]
  workflow_dispatch:  
  schedule:
    - cron: "0 0 * * 1"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: c3e0290e4623ecd3faa587e47cc146f4
          TIMEZONE: Europe/Paris
